version: "3.9"

services:
  caddy:
    image: coloradostark/caddy-ssl-multisite:0.22
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www-data:/var/www
  dbvg:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=vg2021password
      - MYSQL_DATABASE=wordpressDB
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=vg2021password
  dbvr:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=vr2021password
      - MYSQL_DATABASE=wordpressDB
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=vr2021password
  dbtm:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
  environment:
      - MYSQL_ROOT_PASSWORD=tm2021password
      - MYSQL_DATABASE=wordpressDB
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=tm2021password
  wordpressvg:
    depends_on:
      - dbvg
    image: wordpress:5.7
    restart: always
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=vg2021password
      - WORDPRESS_DB_NAME=wordpressDB
    volumes:
      - ./wp-content:/var/www/html/wp-content   
  wordpressvr:
    dependson:
      - dbvr
    image: wordpress:5.7
    restart: always
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=vr2021password
      - WORDPRESS_DB_NAME=wordpressDB
    volumes:
      - ./wp-content:/var/www/html/wp-content   
  wordpresstm:
    depends_on:
      - dbtm
    image: wordpress:5.7
    restart: always
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=tm2021password
      - WORDPRESS_DB_NAME=wordpressDB
    volumes:
      - ./wp-content:/var/www/html/wp-content         
volumes:
  www-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./www-data"
      
  db_data: {}
